name: TravelPortals
main: net.cpprograms.minecraft.TravelPortals.TravelPortals
version: '${minecraft.plugin.version}'
api-version: 1.13
softdepend:
  - Multiverse-Core
  - Multiworld
  - Essentials
  - UUIDDB
commands:
  portal:
    description: Portals
    usage: /portal help
permissions:
  travelportals.nopermission:
    description: Give users no permissions. This may become the new default. Base off of this.
    children: 
      travelportals.portal.create: false
      travelportals.portal.use: false
      travelportals.portal.destroy: false
      travelportals.command.help: false
      travelportals.command.hide: false
      travelportals.command.list: false
      travelportals.command.list.all: false
      travelportals.command.list.others: false
      travelportals.command.name: false
      travelportals.command.warp: false
      travelportals.command.info: false
      travelportals.command.claim: false
      travelportals.admin.portal.use: false
      travelportals.admin.portal.destroy: false
      travelportals.admin.command.name: false
      travelportals.admin.command.warp: false
      travelportals.admin.command.hide: false
  travelportals.classicuser:
    description: User permissions that work like classic TravelPortals; all users have access to all portals.
    children: 
      travelportals.portal.create: true
      travelportals.portal.create.nolimit: true
      travelportals.portal.use: true
      travelportals.portal.destroy: true
      travelportals.command.help: true
      travelportals.command.hide: true
      travelportals.command.list: true
      travelportals.command.list.all: true
      travelportals.command.list.others: true
      travelportals.command.name: true
      travelportals.command.warp: true
      travelportals.command.info: true
      travelportals.command.claim: true
      travelportals.admin.portal.use: true
      travelportals.admin.portal.destroy: true
      travelportals.admin.command.name: true
      travelportals.admin.command.warp: true
      travelportals.admin.command.hide: true
  travelportals.normaluser:
    description: User permissions that limit each user to their own portals
    children: 
      travelportals.portal.create: true
      travelportals.portal.create.nolimit: true
      travelportals.portal.use: true
      travelportals.portal.destroy: true
      travelportals.command.help: true
      travelportals.command.hide: true
      travelportals.command.list: true
      travelportals.command.name: true
      travelportals.command.warp: true
      travelportals.command.info: true
      travelportals.command.claim: true
  travelportals.op:
    description: Suggested permissions for ops. Gives access to most commands
    children:
      travelportals.portal.create: true
      travelportals.portal.create.nolimit: true
      travelportals.portal.use: true
      travelportals.portal.use.crossworld: true
      travelportals.portal.destroy: true
      travelportals.command.help: true
      travelportals.command.hide: true
      travelportals.command.list: true
      travelportals.command.list.all: true
      travelportals.command.list.others: true
      travelportals.command.name: true
      travelportals.command.warp: true
      travelportals.command.warp.crossworld: true
      travelportals.command.info: true
      travelportals.command.info.details: true
      travelportals.command.claim: true
      travelportals.admin.portal.use: true
      travelportals.admin.portal.destroy: true
      travelportals.admin.command.name: true
      travelportals.admin.command.warp: true
      travelportals.admin.command.hide: true
      travelportals.admin.command.deactivate: true
      travelportals.admin.command.claim: true
  travelportals.*:
    description: Gives access to everything. Use with caution.
    children: 
      travelportals.portal.create: true
      travelportals.portal.create.nolimit: true
      travelportals.portal.use: true
      travelportals.portal.use.crossworld: true
      travelportals.portal.destroy: true
      travelportals.command.help: true
      travelportals.command.hide: true
      travelportals.command.list: true
      travelportals.command.list.all: true
      travelportals.command.list.others: true
      travelportals.command.name: true
      travelportals.command.warp: true
      travelportals.command.warp.crossworld: true
      travelportals.command.info: true
      travelportals.command.info.details: true
      travelportals.command.claim: true
      travelportals.admin.portal.use: true
      travelportals.admin.portal.destroy: true
      travelportals.admin.portal.accessall: true
      travelportals.admin.command.name: true
      travelportals.admin.command.warp: true
      travelportals.admin.command.hide: true
      travelportals.admin.command.deactivate: true
      travelportals.admin.command.claim: true
      travelportals.admin.command.export: true
      travelportals.admin.command.reimport: true
      travelportals.admin.command.renameworld: true
      travelportals.admin.command.fixworld: true
      travelportals.admin.command.deleteworld: true
      travelportals.admin.command.reload: true
      travelportals.admin.command.convert: true
  # Here be real permissions
  travelportals.portal.create:
    description: Allows the user to create portals.
    default: true
  travelportals.portal.create.250:
    description: Max portals a user may create
    default: true
  travelportals.portal.create.nolimit:
    description: Allows the user to build as many portals as they like
    default: true
  travelportals.portal.use:
    description: Allows the user to use his/her own portals.
    default: true
  travelportals.portal.use.crossworld:
    description: Allows the user to use their portal between worlds if that is blocked normally.
    default: op
  travelportals.portal.destroy:
    description: Allows the user to destroy his/her own portals.
    default: true
  travelportals.command.help:
    description: Allows the user to see the help.
    default: true
  travelportals.command.list:
    description: Allows the user to see the list of his portals.
    default: true
  travelportals.command.list.all:
    description: Allows the user to see the list of all portals.
    default: true
  travelportals.command.list.others:
    description: Allows the user to see the list of all portals of a specific player.
    default: true
  travelportals.command.name:
    description: Allows the user to name his/her own portals.
    default: true
  travelportals.command.warp:
    description: Allows the user to change the destination of his/her own portals.
    default: true
  travelportals.command.warp.crossworld:
    description: Allows the user to set the warp destination of their portal to another world if that is blocked normally.
    default: op
  travelportals.command.hide:
    description: Allows the user to hide his/her portals.
    default: true
  travelportals.command.claim:
    description: Allows the user to claim unclaimed portals (ones made by older versions)
    default: true
  travelportals.command.info:
    description: Allows the user to get some information about nearby portals.
    default: true
  travelportals.command.info.details:
    description: Allows the user to get some more information about nearby portals.
    default: op
  # Here be dragons.. err, admin permissions
  travelportals.admin.portal.use:
    description: Allows the user to use any existing portals.
    default: true
  travelportals.admin.portal.destroy:
    description: Allows the user to destroy ALL portals; not just his/her own.
    default: op
  travelportals.admin.portal.see:
    description: Allows the user to see any existing portals.
    default: op
  travelportals.admin.command.name:
    description: Allows the user to change the name of any existing portal.
    default: op
  travelportals.admin.command.warp:
    description: Allows the user to change the destination of any existing portal.
    default: op
  travelportals.admin.command.claim:
    description: Allows the user to claim existing portals, EVEN IF THEY ARE ALREADY OWNED.
    default: op
  travelportals.admin.command.deactivate:
    description: Allows staff to clean up portals that may no longer be valid.
    default: op
  travelportals.admin.command.export:
    description: Allows staff to force an export of current warps in txt format.
    default: op
  travelportals.admin.command.import:
    description: Allows staff to import a list of existing warps in the same txt format.
    default: op
